import type { Config } from "tailwindcss";
import daisyui from "daisyui";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
      },
      borderRadius: {
        "4xl": "2rem",
      },
      boxShadow: {
        soft: "0 10px 40px -10px rgb(15 23 42 / 0.08), 0 2px 6px -2px rgb(15 23 42 / 0.04)",
        card: "0 30px 60px -25px rgb(79 70 229 / 0.18), 0 8px 20px -8px rgb(15 23 42 / 0.06)",
        glow: "0 8px 30px -8px rgb(99 102 241 / 0.45)",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.25s ease-out",
        "scale-in": "scale-in 0.2s cubic-bezier(0.16, 1, 0.3, 1)",
        shimmer: "shimmer 2s linear infinite",
      },
      transitionTimingFunction: {
        smooth: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#6366f1",
          "primary-content": "#ffffff",
          secondary: "#a78bfa",
          "secondary-content": "#1f1b3a",
          accent: "#22d3ee",
          "accent-content": "#0b1120",
          neutral: "#1f2937",
          "neutral-content": "#f8fafc",
          "base-100": "#ffffff",
          "base-200": "#f4f5fb",
          "base-300": "#e8eaf3",
          "base-content": "#1f2937",
          info: "#0ea5e9",
          success: "#10b981",
          warning: "#f59e0b",
          error: "#ef4444",
          "--rounded-box": "1.25rem",
          "--rounded-btn": "0.85rem",
          "--rounded-badge": "999px",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-text-case": "none",
          "--border-btn": "0px",
          "--tab-radius": "0.85rem",
        },
        dark: {
          primary: "#818cf8",
          "primary-content": "#0b0d18",
          secondary: "#c4b5fd",
          "secondary-content": "#0b0d18",
          accent: "#22d3ee",
          "accent-content": "#0b1120",
          neutral: "#0f172a",
          "neutral-content": "#e2e8f0",
          "base-100": "#161827",
          "base-200": "#1d2034",
          "base-300": "#272a40",
          "base-content": "#e2e8f0",
          info: "#38bdf8",
          success: "#34d399",
          warning: "#fbbf24",
          error: "#f87171",
          "--rounded-box": "1.25rem",
          "--rounded-btn": "0.85rem",
          "--rounded-badge": "999px",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-text-case": "none",
          "--border-btn": "0px",
          "--tab-radius": "0.85rem",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
} satisfies Config;
